# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/lib/python3.7/site-packages/cmake/data/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /usr/local/lib/python3.7/site-packages/cmake/data/CMake.app/Contents/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/uonliaquat/Desktop/intelliRACE/NN

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/uonliaquat/Desktop/intelliRACE/NN

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/lib/python3.7/site-packages/cmake/data/CMake.app/Contents/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/lib/python3.7/site-packages/cmake/data/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/uonliaquat/Desktop/intelliRACE/NN/CMakeFiles /Users/uonliaquat/Desktop/intelliRACE/NN/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/uonliaquat/Desktop/intelliRACE/NN/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named nn

# Build rule for target.
nn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nn
.PHONY : nn

# fast build rule for target.
nn/fast:
	$(MAKE) -f CMakeFiles/nn.dir/build.make CMakeFiles/nn.dir/build
.PHONY : nn/fast

src/CSV.o: src/CSV.cpp.o

.PHONY : src/CSV.o

# target to build an object file
src/CSV.cpp.o:
	$(MAKE) -f CMakeFiles/nn.dir/build.make CMakeFiles/nn.dir/src/CSV.cpp.o
.PHONY : src/CSV.cpp.o

src/CSV.i: src/CSV.cpp.i

.PHONY : src/CSV.i

# target to preprocess a source file
src/CSV.cpp.i:
	$(MAKE) -f CMakeFiles/nn.dir/build.make CMakeFiles/nn.dir/src/CSV.cpp.i
.PHONY : src/CSV.cpp.i

src/CSV.s: src/CSV.cpp.s

.PHONY : src/CSV.s

# target to generate assembly for a file
src/CSV.cpp.s:
	$(MAKE) -f CMakeFiles/nn.dir/build.make CMakeFiles/nn.dir/src/CSV.cpp.s
.PHONY : src/CSV.cpp.s

src/Matrix.o: src/Matrix.cpp.o

.PHONY : src/Matrix.o

# target to build an object file
src/Matrix.cpp.o:
	$(MAKE) -f CMakeFiles/nn.dir/build.make CMakeFiles/nn.dir/src/Matrix.cpp.o
.PHONY : src/Matrix.cpp.o

src/Matrix.i: src/Matrix.cpp.i

.PHONY : src/Matrix.i

# target to preprocess a source file
src/Matrix.cpp.i:
	$(MAKE) -f CMakeFiles/nn.dir/build.make CMakeFiles/nn.dir/src/Matrix.cpp.i
.PHONY : src/Matrix.cpp.i

src/Matrix.s: src/Matrix.cpp.s

.PHONY : src/Matrix.s

# target to generate assembly for a file
src/Matrix.cpp.s:
	$(MAKE) -f CMakeFiles/nn.dir/build.make CMakeFiles/nn.dir/src/Matrix.cpp.s
.PHONY : src/Matrix.cpp.s

src/NeuralNetwork.o: src/NeuralNetwork.cpp.o

.PHONY : src/NeuralNetwork.o

# target to build an object file
src/NeuralNetwork.cpp.o:
	$(MAKE) -f CMakeFiles/nn.dir/build.make CMakeFiles/nn.dir/src/NeuralNetwork.cpp.o
.PHONY : src/NeuralNetwork.cpp.o

src/NeuralNetwork.i: src/NeuralNetwork.cpp.i

.PHONY : src/NeuralNetwork.i

# target to preprocess a source file
src/NeuralNetwork.cpp.i:
	$(MAKE) -f CMakeFiles/nn.dir/build.make CMakeFiles/nn.dir/src/NeuralNetwork.cpp.i
.PHONY : src/NeuralNetwork.cpp.i

src/NeuralNetwork.s: src/NeuralNetwork.cpp.s

.PHONY : src/NeuralNetwork.s

# target to generate assembly for a file
src/NeuralNetwork.cpp.s:
	$(MAKE) -f CMakeFiles/nn.dir/build.make CMakeFiles/nn.dir/src/NeuralNetwork.cpp.s
.PHONY : src/NeuralNetwork.cpp.s

src/Topology.o: src/Topology.cpp.o

.PHONY : src/Topology.o

# target to build an object file
src/Topology.cpp.o:
	$(MAKE) -f CMakeFiles/nn.dir/build.make CMakeFiles/nn.dir/src/Topology.cpp.o
.PHONY : src/Topology.cpp.o

src/Topology.i: src/Topology.cpp.i

.PHONY : src/Topology.i

# target to preprocess a source file
src/Topology.cpp.i:
	$(MAKE) -f CMakeFiles/nn.dir/build.make CMakeFiles/nn.dir/src/Topology.cpp.i
.PHONY : src/Topology.cpp.i

src/Topology.s: src/Topology.cpp.s

.PHONY : src/Topology.s

# target to generate assembly for a file
src/Topology.cpp.s:
	$(MAKE) -f CMakeFiles/nn.dir/build.make CMakeFiles/nn.dir/src/Topology.cpp.s
.PHONY : src/Topology.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/nn.dir/build.make CMakeFiles/nn.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/nn.dir/build.make CMakeFiles/nn.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/nn.dir/build.make CMakeFiles/nn.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... nn"
	@echo "... src/CSV.o"
	@echo "... src/CSV.i"
	@echo "... src/CSV.s"
	@echo "... src/Matrix.o"
	@echo "... src/Matrix.i"
	@echo "... src/Matrix.s"
	@echo "... src/NeuralNetwork.o"
	@echo "... src/NeuralNetwork.i"
	@echo "... src/NeuralNetwork.s"
	@echo "... src/Topology.o"
	@echo "... src/Topology.i"
	@echo "... src/Topology.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

